export default {
  data: [
    {
      title: '基本信息',
      defaultshow: true,
      items: [
        {
          formItemType: 'SELECT',
          hasAddBtn: true,
          labelcol: 6,
          colSpan: 1,
          fieldcol: 11,
          viewAttr: 3,
          options: [
            {
              disabled: false,
              key: '0',
              selected: true,
              showname: '工作安排',
              visible: true,
            },
            {
              disabled: false,
              key: '1120',
              selected: false,
              showname: 'aaaa',
              visible: true,
            },
            {
              disabled: false,
              key: '1121',
              selected: false,
              showname: '年度计划',
              visible: true,
            },
            {
              disabled: false,
              key: '1122',
              selected: false,
              showname: '临时任务',
              visible: true,
            },
          ],
          conditionType: 'SELECT',
          rules: 'required',
          label: '日程类型',
          domkey: ['workPlanType'],
        },
        {
          formItemType: 'INPUT',
          labelcol: 6,
          colSpan: 1,
          fieldcol: 11,
          viewAttr: 3,
          conditionType: 'INPUT',
          rules: 'required',
          label: '标题',
          value: '',
          domkey: ['planName'],
        },
        {
          formItemType: 'TEXTAREA',
          labelcol: 6,
          colSpan: 1,
          fieldcol: 11,
          viewAttr: 2,
          conditionType: 'TEXTAREA',
          label: '内容',
          hasBorder: true,
          value: '',
          domkey: ['description'],
        },
        {
          formItemType: 'DATEPICKER',
          colSpan: 1,
          fieldcol: 11,
          showTime: true,
          viewAttr: 3,
          format: 'yyyy-MM-dd HH:mm',
          rules: 'required',
          label: '开始日期,时间',
          domkey: ['beginDateTime'],
          mode: 'datetime',
          labelcol: 6,
          conditionType: 'DATEPICKER',
          value: '2020-03-17 00:00',
        },
      ],
    },
  ],
};
